server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 421970
    url: jdbc:postgresql://localhost/movie_app_db_v1
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
      host: smtp.gmail.com
      port: 587
      username: awesomeposta79@gmail.com
      password: Bumerochok1
      properties:
        mail:
          smtp:
            ssl:
              trust: "*"
            auth: true
            starttls:
              enable: true
            connection-timeout: 5000
            timeout: 3000
            write timeout: 5000